# Generated by Django 5.0 on 2023-12-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0003_rename_decription_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
